### ISSUE TITLE
Can't install: no gulpfile found

### ISSUE THREAD

**Issue by joskuijpers** [emedvedev/slackin-extended#1]
Hello,

I tried this package as a replacement for slackin, but I am unable to install it using npm:

```
npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "slackin-extended"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! slackin-extended@1.0.0 postinstall: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slackin-extended@1.0.0 postinstall script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the slackin-extended package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs slackin-extended
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls slackin-extended
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/slackin/npm-debug.log
```

Could you see if you can move all those gulp dependencies into devDependencies? I don't think those should be needed on a published package :) Would make installing it much faster as well.

Thank you for your efforts!

**Comment by emedvedev** [comment]
Hi there,

Thanks for the report, I’ll update as soon as I can!

In the meantime, you can install gulp as a global package, or run the slackin-extended Docker container (I’ve verified that it works).

**Comment by emedvedev** [comment]
@joskuijpers done! 1.1.2 should install fine without gulp or babel or whatever else. Moved everything build-related to `devDependencies`, too — good catch!

**Comment by joskuijpers** [comment]
Thanks! I will try it out.

You don't actually update the code in the repo?

**Comment by joskuijpers** [comment]
Can confirm it works now

**Comment by toolmantim** [comment]
Unfortunately I think this might have broken Heroku support — see #2
