### ISSUE TITLE
Add a robots.txt file

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#119]
Mostly to reduce the 404s

**Comment by emedvedev** [comment]
Where exactly do the robots hit 404s? I don't want to disallow access completely, because it allows people to find some community workspaces that don't have clear links elsewhere, but we can certainly disallow some extra paths if the bots hit them.

**Comment by XhmikosR** [comment]
Hmm, you are right about that. I guess we can drop this for now.
