### ISSUE TITLE
Accepting CoC never succeeds

### ISSUE THREAD

**Issue by raysarebest** [emedvedev/slackin-extended#14]
After setting a link to a CoC, whenever a potential user requests an invite, they will always get an error message saying "Agreement to CoC is mandatory", even if they've checked the box to agree to the code of conduct

This is due to the fact that the branch where that error is generated (line 200 of index.js), the code currently checks to see if the value of `req.body.coc` is strictly equal to the string `'1'`, but it's actual value is the number `1`. Since it's not the same type, strict equality checking fails, but loose equality checking would succeed

A reasonable fix to this would be to loosely check for equality, so it doesn't matter if it's coming in as a string or a number. Alternatively, the code could strictly check for the number `1`

**Comment by emedvedev** [comment]
Thank you! Not sure how it was overlooked; merged the PR. :)

**Comment by raysarebest** [comment]
Awesome, thanks! I'd love to see this get published to NPM so it's there whenever I run `npm upgrade -g` again 🙂

**Comment by emedvedev** [comment]
All done :)

**Comment by XhmikosR** [comment]
We should have a test for this :)
