### ISSUE TITLE
Add a Heroku button

### ISSUE THREAD

**Issue by emedvedev** [emedvedev/slackin-extended#142]
Should get to it after the release.

@XhmikosR does the Heroku deploy work as expected, or should something else be fixed before I add the button?

**Comment by XhmikosR** [comment]
Yeah it works for me just fine with the env vars: https://bootstrap-slack.herokuapp.com/

**Comment by XhmikosR** [comment]
BTW ideally we should move devDependencies in devDependencies, I just moved Sass etc in dependencies so that we skip the extra step when deploying on Heroku. I don't like either way, so it's your call
