### ISSUE TITLE
Heroku: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by marcelfolaron** [emedvedev/slackin-extended#148]
Aftwer typing in the email and submitting the form I see a javascript error. The button is greyed out and nothing happens. (A slack invite is sent out though!) 
`
Uncaught TypeError: Cannot read property 'body' of null
    at client.js:55
    at Request.callback (superagent.js:1723)
    at Request.<anonymous> (superagent.js:1550)
    at Request.Emitter.emit (superagent.js:1080)
    at XMLHttpRequest.xhr.onreadystatechange (superagent.js:1817)
`

```
function invite(chan, coc, email, gcaptcha_response_value, fn) {
  request
    .post(data.path + 'invite')
    .send({
      'g-recaptcha-response': gcaptcha_response_value,
      coc: coc,
      channel: chan,
      email: email
    })
    .end(function (res) {
      if (res.body.redirectUrl) {
        window.setTimeout(function () {
          topLevelRedirect(res.body.redirectUrl)
        }, 1500)
      }
      if (res.error) {
        return fn(new Error(res.body.msg || 'Server error'))
      }
      fn(null, res.body.msg)
    })
}
```

**Comment by marcelfolaron** [comment]
Looking at the server response there is only  "msg" not "redirectURL"

**Comment by emedvedev** [comment]
Thanks for the report, I’ll look into it!
Are you running the latest version? When have you deployed it? The new one was just released today, so if it was earlier than that, please try updating.

**Comment by marcelfolaron** [comment]
New version worked! Thank you!
