### ISSUE TITLE
Badge cutoff

### ISSUE THREAD

**Issue by Mokto** [emedvedev/slackin-extended#182]
See the readme here https://github.com/komakio/app

<img width="139" alt="Screenshot 2020-04-02 at 08 03 07" src="https://user-images.githubusercontent.com/5103928/78215701-6aa19400-74b8-11ea-8bce-df1eac174647.png">

Thanks!

**Comment by emedvedev** [comment]
Hi there! Could you tell me which version you're using and how you're deploying it? I think I remember this issue being fixed a while ago, but I'll double-check, just need to make sure you're using the latest verion.

**Comment by Mokto** [comment]
My bad, I was installing it through a [BanzaiCloud fork](https://github.com/banzaicloud/slackin-extended). Because I wanted to use their helm chart.

I just switched to the docker image that you just pushed, and everything is fine now :)

Thanks!
