### ISSUE TITLE
Npm install can break server-side path to client-side dependency /assets/superagent.js

### ISSUE THREAD

**Issue by joelpurra** [emedvedev/slackin-extended#185]
The client-side dependency `/assets/superagent.js` is given special server-side path treatment in `index.js`.

- https://github.com/emedvedev/slackin-extended/blob/v2.1.0/lib/index.js#L128

On my system `/assets/superagent.js` returns HTTP error 404 and breaks `slackin-extended` client-side. This is due to (changes in) how `npm install` places dependencies, which _may_ be optimized between packages in the same `package.json`.

- https://slackin.joelpurra.com/

<details>
<summary>Versions</summary>

Am running slightly older versions due to `apt` on Debian 10 Buster.

```shell
node --version
```

```text
v10.15.2
```

```shell
npm --version
```

```text
6.14.4
```

</details>

<details>
<summary>Paths</summary>

```shell
npm ls superagent
```

```text
slackin.joelpurra.com@1.0.0 .../slackin.joelpurra.com/public_html
└─┬ slackin-extended@2.1.0
  └── superagent@3.8.3 
```

```shell
ls --format=long --directory ./node_modules/{slackin-extended,superagent}
```

```text
drwxr-xr-x 1 root root 116 Apr  8 16:56 ./node_modules/slackin-extended
drwxr-xr-x 1 root root 282 Apr  8 16:56 ./node_modules/superagent
```

</details>

Perhaps something like `resolve-pkg` could be used in the short-term, but replacing `superagent` with something else might be a better long-term solution. See also #86.

- https://github.com/sindresorhus/resolve-pkg

_Originally posted by @joelpurra in https://github.com/emedvedev/slackin-extended/issues/86#issuecomment-611086791_

**Comment by XhmikosR** [comment]
Can you try this branch please? https://github.com/XhmikosR/slackin-extended/tree/fix-superagent

**Comment by joelpurra** [comment]
@XhmikosR: due to the locked-down nature of the particular system where the issue was discovered, I can't test your branch in the exact same way as before.

Tested (without the production slack configuration) on a dev machine (with the same/similar `node-modules` structure; slightly abbreviated below) though, and the resolved `superagentDist` in the log output points to the correct file on disk. Should work!

<details>
<summary>Versions</summary>

```shell
node --version
```

```text
v12.16.1
```

```shell
npm --version
```

```text
6.13.4
```

</details>

<details>
<summary>Paths</summary>

```shell
npm ls superagent
```

```text
slackin-extended-test@1.0.0 .../slackin-extended-test
└─┬ slackin-extended@2.1.0 (github:XhmikosR/slackin-extended#72003bf158cc7cfd2f9997451815fc079948234c)
  └── superagent@3.8.3
```

```shell
ls -l -d ./node_modules/{slackin-extended,superagent}
```

```text
drwxr-xr-x  10 joelpurra  staff  320 Apr  8 20:35 ./node_modules/slackin-extended
drwxr-xr-x  17 joelpurra  staff  544 Apr  8 20:35 ./node_modules/superagent
```

</details>

```text
>> superagentDist: .../slackin-extended-test/node_modules/superagent/superagent.js
```

**Comment by XhmikosR** [comment]
Cool, it was easier to fix than I thought then 🙂

PR: #187

**Comment by emedvedev** [comment]
Thank you :) Let me test the PR and merge.
