### ISSUE TITLE
Update Node.js to 14.x

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#195]
Node.js 14.x has some nice improvements and it's the current LTS: https://nodejs.org/en/about/releases/

I'm opening this issue so that the version is updated for all deployments. I only deploy on Heroku and I'm using 14.x since the beginning I switched to slackin-extended, but this should be done for all deployments like Docker, Azure etc

**Comment by XhmikosR** [comment]
For what is worth, I've been using 14.x for months without any issues.

**Comment by XhmikosR** [comment]
@emedvedev might want to tackle this too? Node.js 14.x is quite stable. I can submit a PR, but I'm not sure about the Azure deployment etc, since I only use Heroku myself.

**Comment by emedvedev** [comment]
Available since November on Azure it looks like, so if you could create a PR that'd be great! Thanks a lot for the updates :)
