### ISSUE TITLE
Doesn't work on Heroku

### ISSUE THREAD

**Issue by toolmantim** [emedvedev/slackin-extended#2]
Thanks for the fork! I was a contributor to the original slackin repo.

I've had some trouble getting this up and running on Heroku, but I didn't want to send through a pull request because it has to do with the build process, and didn't know what you wanted to do about it.

Basically, this fails to run on Heroku now because there's no `dist` folder.

Firstly, the package.json needs some kind of build statement that Heroku recognises (`post-install` or `heroku-postbuild` so that it can run gulp and generate the dist on dyno building). For example:

```diff
diff --git a/package.json b/package.json
index 8c4680f..bc3cc5c 100644
--- a/package.json
+++ b/package.json
@@ -62,7 +62,8 @@
   "scripts": {
     "test": "mocha && eslint lib/**",
     "build": "gulp",
-    "start": "./bin/slackin"
+    "start": "./bin/slackin",
+    "heroku-postbuild": "gulp"
   },
   "now": {
     "type": "npm",
```

Secondly, because gulp is listed as a dev dependency, it's not installed in the dyno and the build still fails. The fix for that was to run set the environment variable `NPM_CONFIG_PRODUCTION=false`

**Comment by joskuijpers** [comment]
Why does Heroku require to build it at all, and if it does why doesn't it install the dev dependencies?

Can't Heroku pull from npm?

**Comment by emedvedev** [comment]
@toolmantim Thanks for the report!

Could you confirm this would work?
```
"heroku-prebuild": "npm install --only=dev",
"heroku-postbuild": "gulp"
```

Might be slightly better, since it'd work by default without changing env variables.

**Comment by toolmantim** [comment]
@emedvedev ah of course! Nice suggestion. Yep, I just tested (with the removed env) and works a treat. Submitted a PR 🙌🏼

**Comment by emedvedev** [comment]
Perfect, thanks a lot for the help!
