### ISSUE TITLE
Add lgtm.com to the repo

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#29]
lgtm.com is now owned by GitHub. It's a good addition to linting and it has already found real issues: https://lgtm.com/projects/g/emedvedev/slackin-extended/?mode=list

Note that many of the assets issues will be fixed by #25

**Comment by emedvedev** [comment]
Done! Should be enabled for all new PRs.

**Comment by XhmikosR** [comment]
@emedvedev just remember to disable PR comments; the check will fail anyway. Do you want to add a README.md badge?
