### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by ManuTheCoder** [emedvedev/slackin-extended#343]
Sorry for posting here, but I cannot access your site!
![image](https://user-images.githubusercontent.com/77016441/108789866-1bc97680-7530-11eb-8d6c-d1ee444b233e.png)
Here is something that might help:

> 500: INTERNAL_SERVER_ERROR
> Code: FUNCTION_INVOCATION_FAILED
> ID: sfo1::n7knp-1614042256050-f8ab90846f60

**Comment by XhmikosR** [comment]
Yeah, it's broken for quite some time @emedvedev

**Comment by ManuTheCoder** [comment]
Oh, Ok
