### ISSUE TITLE
assets/superagent.js

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#58]
Is this https://github.com/visionmedia/superagent?

It seems it's the same code, some pretty old version. If so, we shouldn't have touched the file and ignore it in linting. Instead we should use the npm dist file directly.

@emedvedev can you confirm the above?

**Comment by emedvedev** [comment]
I think it might be, yeah. Which is weird, because it's also listed as a dependency in package.json.

**Comment by XhmikosR** [comment]
The dep in package.json is for Node not the frontend :)

I made #59, but I cannot test it. It should work on modern browsers + IE >= 10

**Comment by emedvedev** [comment]
I mean that it could be reused for the frontend as well—exactly what you did in #59 :) I should be able to test a bit later this week.
