### ISSUE TITLE
Demo and PR previews

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#64]
It seems the [current demo](https://slackin.now.sh/) does not use this package.

Also, how about adding Now for PR previews?

**Comment by XhmikosR** [comment]
@emedvedev can we get a demo set up with the latest npm published version? Even if we don't have PR previews for now.

I'd like to run some comparison tests.

**Comment by XhmikosR** [comment]
@emedvedev maybe make Zeit not comment on PRs? :)

**Comment by emedvedev** [comment]
It's work in progress :)

**Comment by emedvedev** [comment]
All done.
