### ISSUE TITLE
res.body is undefined

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#99]
@emedvedev I was trying to register on the demo Slack (so that maybe we can chat in real time :P) but I get this and nothing happens

```
TypeError: res.body is undefined client.js:55:11
    invite https://slackin-extended.emedvedev.now.sh/assets/client.js:55
    callback https://slackin-extended.emedvedev.now.sh/assets/superagent.js:1723
    Request https://slackin-extended.emedvedev.now.sh/assets/superagent.js:1548
    emit https://slackin-extended.emedvedev.now.sh/assets/superagent.js:1080
    onreadystatechange https://slackin-extended.emedvedev.now.sh/assets/superagent.js:1817
```

I believe it's an issue with the deployment, but regardless... The POST response seems to be

```
{"msg":"not_allowed_token_type"}
```

So, I guess we need to tweak the client JS too so that we catch this properly. Not sure if it worked before with the old superagent client version or if it's a new regression from #59.

Might be worth just switching to XHR sooner than later while at it, assuming it worked before #59.

**Comment by emedvedev** [comment]
Oh, it's not the client, this is an issue with the token I've got from Slack—apparently bot tokens now have a scope that doesn't allow issuing invites.

We could catch this error and handle it better, but actually it's an error only the administrator is going to see, and only during setup, so I'd say it's very low in priority.

**Comment by XhmikosR** [comment]
I say it in the docs that a legacy token is needed :P
